### ISSUE TITLE
OverflowError: value too large to convert to short

### ISSUE THREAD

**Issue by simjbaum** [macs3-project/MACS#125]
Hello,
I saw a similar error in the questions of this repository some times but could not find a solution, could you please help?

 Command line: callpeak -t CHD1_K562_mergedm1k1.bam -f BAM -g hs -n CHD1
 ARGUMENTS LIST:
 name = CHD1
 format = BAM
 ChIP-seq file = ['CHD1_K562_mergedm1k1.bam']
 control file = None
 effective genome size = 2.70e+09
 band width = 300
 model fold = [5, 50]
 qvalue cutoff = 5.00e-02
 Larger dataset will be scaled towards smaller dataset.
 Range for calculating regional lambda is: 10000 bps
 Broad region calling is off
 Paired-End mode is off

INFO  @ Tue, 19 Apr 2016 00:08:45: #1 read tag files... 
INFO  @ Tue, 19 Apr 2016 00:08:45: #1 read treatment tags... 
Exception struct.error: 'unpack requires a string argument of length 4' in 'MACS2.IO.Parser.BAMParser.tsize' ignored
Traceback (most recent call last):
  File "/usr/local/bin/macs2", line 617, in <module>
    main()
  File "/usr/local/bin/macs2", line 57, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/callpeak_cmd.py", line 73, in run
    else:       (treat, control) = load_tag_files_options  (options)
  File "/usr/local/lib/python2.7/dist-packages/MACS2/callpeak_cmd.py", line 399, in load_tag_files_options
    treat = tp.build_fwtrack()
  File "MACS2/IO/Parser.pyx", line 880, in MACS2.IO.Parser.BAMParser.build_fwtrack (MACS2/IO/Parser.c:13703)
  File "MACS2/IO/Parser.pyx", line 903, in MACS2.IO.Parser.BAMParser.build_fwtrack (MACS2/IO/Parser.c:13365)
  File "MACS2/IO/Parser.pyx", line 964, in MACS2.IO.Parser.BAMParser.__fw_binary_parse (MACS2/IO/Parser.c:14669)
OverflowError: value too large to convert to short

Thanks

**Comment by philippadoherty** [comment]
Closing this issue as "stale" due to inactivity.
