### ISSUE TITLE
macs2 callpeak error!

### ISSUE THREAD

**Issue by DrPraRam** [macs3-project/MACS#210]
Hi there,

I am new to ATAC-seq data analysis. I have installed MACS2 using pip. I just ran callpeak function using treated and control bam files. I used the following command:
macs2 callpeak -t K-P-1.mapQabove10.RG.marked.sorted.bam -c K-P-9.mapQabove10.RG.marked.sorted.bam -f BAM -g hs -n K-P-1 -B -q 0.01

I am getting the following message and error:

Traceback (most recent call last):
  File "/mnt/DATAPART3/local/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.1.20160309', 'macs2')
  File "/mnt/DATAPART3/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/mnt/DATAPART3/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/wenbin/.local/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 617, in <module>
    
  File "/home/wenbin/.local/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main
    
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 31, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/OptValidator.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/IO/Parser.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/MACS2/IO/Parser.py", line 6, in __bootstrap__
ImportError: /home/wenbin/.cache/Python-Eggs/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg-tmp/MACS2/IO/Parser.so: undefined symbol: PyFPE_jbuf

Please advice me on this. Thank you.

BR,
P

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
