### ISSUE TITLE
struct.error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by Belsufu** [macs3-project/MACS#260]
I am having this issue but I do not know why exactly.
Could you help me?
Thank you in advance

INFO  @ Fri, 28 Sep 2018 22:39:33: 
# Command line: callpeak -t AndrewCD38LowR1.BedUtils.bed -f BED --format BAMPE -n BAMPEAndrewCD38Low_ -g hs
# ARGUMENTS LIST:
# name = BAMPEAndrewCD38Low_
# format = BAMPE
# ChIP-seq file = ['AndrewCD38LowR1.BedUtils.bed']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is on
 
INFO  @ Fri, 28 Sep 2018 22:39:33: #1 read fragment files... 
INFO  @ Fri, 28 Sep 2018 22:39:33: #1 read treatment fragments... 
Traceback (most recent call last):
  File "/n/app/macs2/2.1.1.20160309/bin/macs2", line 4, in <module>
    __import__('pkg_resources').run_script('MACS2==2.1.1.20160309', 'macs2')
  File "/n/app/python/2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/n/app/python/2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/n/app/macs2/2.1.1.20160309/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 617, in <module>
    
  File "/n/app/macs2/2.1.1.20160309/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 57, in main
    
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 72, in run
  File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 358, in load_frag_files_options
  File "MACS2/IO/Parser.pyx", line 1024, in MACS2.IO.Parser.BAMPEParser.build_petrack (MACS2/IO/Parser.c:15888)
  File "MACS2/IO/Parser.pyx", line 1041, in MACS2.IO.Parser.BAMPEParser.build_petrack (MACS2/IO/Parser.c:15269)
  File "MACS2/IO/Parser.pyx", line 869, in MACS2.IO.Parser.BAMParser.get_references (MACS2/IO/Parser.c:12733)
struct.error: unpack requires a string argument of length 4

**Comment by taoliu** [comment]
Because you used this options: "-t AndrewCD38LowR1.BedUtils.bed -f BED --format BAMPE" You have a bed file but you asked MACS2 to read it as BAM file. Try to remove "--format BAMPE" part.

**Comment by NishatTamana51** [comment]
**Thanks.** I did the same error. Your solution helped me.

**Comment by scyrusm** [comment]
Hi there,

I am getting the same error, but with an apparently different cause:
`hmmratac -i test.bam -f BAMPE --outdir HmmratacOutput/ -n test`
yields

> Command line: hmmratac -i test.bam -f BAMPE --outdir HmmratacOutput/ -n test
> Random seed selected as: 10151 Use --hmm-type to select a Gaussian ('gaussian') or Poisson ('poisson') model for the hidden > markov model in HMMRATAC. Default: 'gaussian'. 
 
> INFO  @ 25 Sep 2024 09:00:49: [128 MB] #1 Read fragments from BAMPE file... 
> Traceback (most recent call last):
  File "/home/sm654/miniconda3/bin/macs3", line 983, in <module>
    main()
  File "/home/sm654/miniconda3/bin/macs3", line 97, in main
    run( args )
  File "/home/sm654/miniconda3/lib/python3.9/site-packages/MACS3/Commands/hmmratac_cmd.py", line 97, in run
    petrack = alignment.build_petrack()
  File "MACS3/IO/Parser.pyx", line 1304, in MACS3.IO.Parser.BAMPEParser.build_petrack
  File "MACS3/IO/Parser.pyx", line 1318, in MACS3.IO.Parser.BAMPEParser.build_petrack
  File "MACS3/IO/Parser.pyx", line 1203, in MACS3.IO.Parser.BAMParser.get_references
struct.error: unpack requires a buffer of 4 bytes`

This is with macs3 v3.0.2.  Do you have any sense of whether this is a problem with the .bam file I am processing, or something with macs3 hmmratac?
