### ISSUE TITLE
Bug: OverflowError: value too large to convert to int

### ISSUE THREAD

**Issue by liu3zhenlab** [macs3-project/MACS#404]
I know this the old issue. But I still cannot find the solution.

I installed macs2 through conda (conda install -c bioconda macs2). The 64bit environment was created. The version macs2 2.2.7.1 was installed.

"macs2 callpeak" was run on maize data, which has ~2.3 Gb genome.

Here is the error I received:

Traceback (most recent call last):
  File ".conda/envs/macs2/bin/macs2", line 653, in <module>
    main()
  File ".conda/envs/macs2/bin/macs2", line 51, in main
    run( args )
  File "conda/envs/macs2/lib/python3.7/site-packages/MACS2/callpeak_cmd.py", line 170, in run
    opt = options
  File "MACS2/PeakModel.pyx", line 105, in MACS2.PeakModel.PeakModel.__init__
  File "MACS2/PeakModel.pyx", line 120, in MACS2.PeakModel.PeakModel.build
OverflowError: value too large to convert to int

Appreciated your comments. Thanks.

**Comment by liu3zhenlab** [comment]
Sorry, I accidentally specified "-g 1e-9". After correcting it to "-g 1e9", the issue was gone.
