### ISSUE TITLE
Bug: Install Error using pip3 install

### ISSUE THREAD

**Issue by lufuhao** [macs3-project/MACS#420]
**Describe the bug**
A error happened when using pip3 install on my ubuntu20.04 with gcc9.3.0

**To Reproduce**
pip3 install --user macs2

**Expected behavior**
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple/, https://pypi.tuna.tsinghua.edu.cn/simple
Collecting macs2
  Downloading https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/e2/61/85d30ecdd34525113e28cb0c5a9f393f93578165f8d848be5925c0208dfb/MACS2-2.2.7.1.tar.gz (2.1 MB)
     |████████████████████████████████| 2.1 MB 713 kB/s 
  ERROR: Error expected str, bytes or os.PathLike object, not NoneType while executing command /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /var/tmp/pip-build-env-zlje73qm/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.mirrors.ustc.edu.cn/simple/ --extra-index-url https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.mirrors.ustc --trusted-host '' --trusted-host pypi.tuna.tsinghua -- pip 'setuptools>=41.2' 'numpy>=1.17' 'cython>=0.29' wheel
  Installing build dependencies ... error
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 515, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/usr/lib/python3/dist-packages/pip/_internal/distributions/sdist.py", line 66, in _setup_isolation
    self.req.build_env.install_requirements(
  File "/usr/lib/python3/dist-packages/pip/_internal/build_env.py", line 201, in install_requirements
    call_subprocess(args, spinner=spinner)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 186, in call_subprocess
    proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Linux ubuntu20]
 - Python version [e.g. 3.8.5]
 - Numpy version [e.g. 1.19.2]
 - MACS Version [e.g. 2.2.7.1]

**Additional context**
NO

**Comment by taoliu** [comment]
@lufuhao  It seems there is some problem in your python environment. The error appeared while installing dependencies. Try to install the dependencies by yourself for numpy and cython. Then download the macs2 source code by `pip download` instead of `pip install`, and install it from source code by `python setup.py install`
