### ISSUE TITLE
Macs2 inconsistent.  Sometimes it works. sometimes it doesnt. 

### ISSUE THREAD

**Issue by danielcgingerich** [macs3-project/MACS#453]
Ok, whats going on here?  Sometimes macs2 works; sometimes it doesn't.  I changed nothing about my code.  You can even look at the command line in both outputs below and see they are the exact same, aside from the tmp directory.  

I am using the Signac wrapper for macs2.  Signac (R package) is an extension of Seurat (R package), used for single cell data analysis.  Signac first splits my fragment file by cell type and puts the new .bed file into a tmp directory, which is fed to macs2.  I am submitting 144 macs2 jobs as a slurm array.  I thought the issue could be that there were too many tmp directories being created at the same time.  Nope.  After using a loop instead of parallel computing, the same error still occurs.  

Here is the output from a failed run: 

```
INFO  @ Wed, 21 Apr 2021 11:42:50: 
# Command line: callpeak -t /tmp/RtmpSWcxw9/Astro.bed -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n Astro --outdir /gpfs/fs1/data/chiba-faleklab/Daniel/snATAC.snRNA.R01.v2/R.objects/recalled.peaks/astro2/99/
# ARGUMENTS LIST:
# name = Astro
# format = BED
# ChIP-seq file = ['/tmp/RtmpSWcxw9/Astro.bed']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Wed, 21 Apr 2021 11:42:50: #1 read tag files... 
INFO  @ Wed, 21 Apr 2021 11:42:50: #1 read treatment tags... 
Exception ZeroDivisionError: 'integer division or modulo by zero' in 'MACS2.IO.Parser.GenericParser.tsize' ignored
INFO  @ Wed, 21 Apr 2021 11:42:50: #1 tag size is determined as 0 bps 
INFO  @ Wed, 21 Apr 2021 11:42:50: #1 tag size = 0.0 
INFO  @ Wed, 21 Apr 2021 11:42:50: #1  total tags in treatment: 0 
INFO  @ Wed, 21 Apr 2021 11:42:50: #1 user defined the maximum tags... 
INFO  @ Wed, 21 Apr 2021 11:42:50: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
INFO  @ Wed, 21 Apr 2021 11:42:50: #1  tags after filtering in treatment: 0 
Traceback (most recent call last):
  File "/nfs/software/helmod/apps/Core/macs2/2.1.2.20181108-gcb01/bin/macs2", line 622, in <module>
    main()
  File "/nfs/software/helmod/apps/Core/macs2/2.1.2.20181108-gcb01/bin/macs2", line 57, in main
    run( args )
  File "/nfs/software/helmod/apps/Core/macs2/2.1.2.20181108-gcb01/lib/python2.7/site-packages/MACS2/callpeak_cmd.py", line 112, in run
    info("#1  Redundant rate of treatment: %.2f", float(t0 - t1) / t0)
ZeroDivisionError: float division by zero
Error in file(file, "rt") : cannot open the connection
Calls: CallPeaks ... CallPeaks -> CallPeaks.default -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/gpfs/fs1/data/chiba-faleklab/Daniel/snATAC.snRNA.R01.v2/R.objects/recalled.peaks/astro2/99//Astro_peaks.narrowPeak': No such file or directory
Execution halted
```

Here is the same exact code, but it works: 

```
INFO  @ Wed, 21 Apr 2021 13:02:14: 
# Command line: callpeak -t /tmp/RtmpaQeXyt/Astro.bed -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n Astro --outdir /gpfs/fs1/data/chiba-faleklab/Daniel/snATAC.snRNA.R01.v2/R.objects/recalled.peaks/astro2/99/
# ARGUMENTS LIST:
# name = Astro
# format = BED
# ChIP-seq file = ['/tmp/RtmpaQeXyt/Astro.bed']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
# The maximum gap between significant sites is assigned as the read length/tag size.
# The minimum length of peaks is assigned as the predicted fragment length "d".
# Larger dataset will be scaled towards smaller dataset.
# Range for calculating regional lambda is: 10000 bps
# Broad region calling is off
# Paired-End mode is off
 
INFO  @ Wed, 21 Apr 2021 13:02:14: #1 read tag files... 
INFO  @ Wed, 21 Apr 2021 13:02:14: #1 read treatment tags... 
INFO  @ Wed, 21 Apr 2021 13:02:16:  1000000 
INFO  @ Wed, 21 Apr 2021 13:02:18:  2000000 
INFO  @ Wed, 21 Apr 2021 13:02:19:  3000000 
INFO  @ Wed, 21 Apr 2021 13:02:21:  4000000 
INFO  @ Wed, 21 Apr 2021 13:02:22:  5000000 
INFO  @ Wed, 21 Apr 2021 13:02:24:  6000000 
INFO  @ Wed, 21 Apr 2021 13:02:26:  7000000 
INFO  @ Wed, 21 Apr 2021 13:02:27:  8000000 
INFO  @ Wed, 21 Apr 2021 13:02:29:  9000000 
INFO  @ Wed, 21 Apr 2021 13:02:30:  10000000 
INFO  @ Wed, 21 Apr 2021 13:02:32:  11000000 
INFO  @ Wed, 21 Apr 2021 13:02:33:  12000000 
INFO  @ Wed, 21 Apr 2021 13:02:35:  13000000 
INFO  @ Wed, 21 Apr 2021 13:02:36:  14000000 
INFO  @ Wed, 21 Apr 2021 13:02:38:  15000000 
INFO  @ Wed, 21 Apr 2021 13:02:40:  16000000 
INFO  @ Wed, 21 Apr 2021 13:02:41:  17000000 
INFO  @ Wed, 21 Apr 2021 13:02:43:  18000000 
INFO  @ Wed, 21 Apr 2021 13:02:44:  19000000 
INFO  @ Wed, 21 Apr 2021 13:02:46:  20000000 
INFO  @ Wed, 21 Apr 2021 13:02:48:  21000000 
INFO  @ Wed, 21 Apr 2021 13:02:49:  22000000 
INFO  @ Wed, 21 Apr 2021 13:02:51:  23000000 
INFO  @ Wed, 21 Apr 2021 13:02:52:  24000000 
INFO  @ Wed, 21 Apr 2021 13:02:54:  25000000 
INFO  @ Wed, 21 Apr 2021 13:02:55:  26000000 
INFO  @ Wed, 21 Apr 2021 13:02:56:  27000000 
INFO  @ Wed, 21 Apr 2021 13:02:58:  28000000 
INFO  @ Wed, 21 Apr 2021 13:02:59:  29000000 
INFO  @ Wed, 21 Apr 2021 13:03:01:  30000000 
INFO  @ Wed, 21 Apr 2021 13:03:02:  31000000 
INFO  @ Wed, 21 Apr 2021 13:03:04:  32000000 
INFO  @ Wed, 21 Apr 2021 13:03:05:  33000000 
INFO  @ Wed, 21 Apr 2021 13:03:07:  34000000 
INFO  @ Wed, 21 Apr 2021 13:03:08:  35000000 
INFO  @ Wed, 21 Apr 2021 13:03:10:  36000000 
INFO  @ Wed, 21 Apr 2021 13:03:12:  37000000 
INFO  @ Wed, 21 Apr 2021 13:03:13:  38000000 
INFO  @ Wed, 21 Apr 2021 13:03:15:  39000000 
INFO  @ Wed, 21 Apr 2021 13:03:16:  40000000 
INFO  @ Wed, 21 Apr 2021 13:03:18:  41000000 
INFO  @ Wed, 21 Apr 2021 13:03:19:  42000000 
INFO  @ Wed, 21 Apr 2021 13:03:21:  43000000 
INFO  @ Wed, 21 Apr 2021 13:03:22:  44000000 
INFO  @ Wed, 21 Apr 2021 13:03:24:  45000000 
INFO  @ Wed, 21 Apr 2021 13:03:25:  46000000 
INFO  @ Wed, 21 Apr 2021 13:03:27:  47000000 
INFO  @ Wed, 21 Apr 2021 13:03:28:  48000000 
INFO  @ Wed, 21 Apr 2021 13:03:29: #1 tag size is determined as 138 bps 
INFO  @ Wed, 21 Apr 2021 13:03:29: #1 tag size = 138.0 
INFO  @ Wed, 21 Apr 2021 13:03:29: #1  total tags in treatment: 48060470 
INFO  @ Wed, 21 Apr 2021 13:03:29: #1 user defined the maximum tags... 
INFO  @ Wed, 21 Apr 2021 13:03:29: #1 filter out redundant tags at the same location and the same strand by allowing at most 1 tag(s) 
INFO  @ Wed, 21 Apr 2021 13:03:30: #1  tags after filtering in treatment: 40448582 
INFO  @ Wed, 21 Apr 2021 13:03:30: #1  Redundant rate of treatment: 0.16 
INFO  @ Wed, 21 Apr 2021 13:03:30: #1 finished! 
INFO  @ Wed, 21 Apr 2021 13:03:30: #2 Build Peak Model... 
INFO  @ Wed, 21 Apr 2021 13:03:30: #2 Skipped... 
INFO  @ Wed, 21 Apr 2021 13:03:30: #2 Use 200 as fragment length 
INFO  @ Wed, 21 Apr 2021 13:03:30: #2 Sequencing ends will be shifted towards 5' by 100 bp(s) 
INFO  @ Wed, 21 Apr 2021 13:03:30: #3 Call peaks... 
INFO  @ Wed, 21 Apr 2021 13:03:30: #3 Pre-compute pvalue-qvalue table... 
INFO  @ Wed, 21 Apr 2021 13:05:28: #3 Call peaks for each chromosome... 
INFO  @ Wed, 21 Apr 2021 13:06:57: #4 Write output xls file... /gpfs/fs1/data/chiba-faleklab/Daniel/snATAC.snRNA.R01.v2/R.objects/recalled.peaks/astro2/99/Astro_peaks.xls 
INFO  @ Wed, 21 Apr 2021 13:06:58: #4 Write peak in narrowPeak format file... /gpfs/fs1/data/chiba-faleklab/Daniel/snATAC.snRNA.R01.v2/R.objects/recalled.peaks/astro2/99/Astro_peaks.narrowPeak 
INFO  @ Wed, 21 Apr 2021 13:06:59: #4 Write summits bed file... /gpfs/fs1/data/chiba-faleklab/Daniel/snATAC.snRNA.R01.v2/R.objects/recalled.peaks/astro2/99/Astro_summits.bed 
INFO  @ Wed, 21 Apr 2021 13:06:59: Done! 

```

From the output above, the command line input given to macs2 from signac is identical (see below).  Why is one failing while the other does not?  

```
# Command line: callpeak -t /tmp/RtmpSWcxw9/Astro.bed -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n Astro --outdir /gpfs/fs1/data/chiba-faleklab/Daniel/snATAC.snRNA.R01.v2/R.objects/recalled.peaks/astro2/99/
# ARGUMENTS LIST:
# name = Astro
# format = BED
# ChIP-seq file = ['/tmp/RtmpSWcxw9/Astro.bed']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02

# Command line: callpeak -t /tmp/RtmpaQeXyt/Astro.bed -g 2.7e+09 -f BED --nomodel --extsize 200 --shift -100 -n Astro --outdir /gpfs/fs1/data/chiba-faleklab/Daniel/snATAC.snRNA.R01.v2/R.objects/recalled.peaks/astro2/99/
# ARGUMENTS LIST:
# name = Astro
# format = BED
# ChIP-seq file = ['/tmp/RtmpaQeXyt/Astro.bed']
# control file = None
# effective genome size = 2.70e+09
# band width = 300
# model fold = [5, 50]
# qvalue cutoff = 5.00e-02
```

**Comment by taoliu** [comment]
Hi @danielcgingerich, the 'temporary file provided by Signac seems different: the one `/tmp/RtmpSWcxw9/Astro.bed` seems to be empty while `/tmp/RtmpaQeXyt/Astro.bed` seems to be valid. How about copy those two files out of the `tmp` directory and try to investigate them?
