### ISSUE TITLE
BAMPE for CUT&RUN paired end data gives me "AssertionError: 1000 can't be smaller than" with both macs2 and macs3

### ISSUE THREAD

**Issue by pialim** [macs3-project/MACS#468]
I am using MACS to call peaks for CUT&RUN data aligned with bwa (sorted and indexed bam files).
I am get the following errors with the included commands:

**MACS3**
macs3 callpeak -f BAMPE -t bams/31Corr-Day2_H3K4me3_PF.maxL.bam -c bams/31Corr-Day1_IgG_PF.maxL.bam --outdir peaks -g hs -n 31Corr-Day2 -B -q 0.05

**ERROR:**
INFO  @ Wed, 14 Jul 2021 17:38:08: 22663234 fragments have been read. 
INFO  @ Wed, 14 Jul 2021 17:38:22: #1 mean fragment size is determined as 10303.2 bp from treatment 
INFO  @ Wed, 14 Jul 2021 17:38:22: #1 note: mean fragment size in control is 16011.8 bp -- value ignored 
INFO  @ Wed, 14 Jul 2021 17:38:22: #1 fragment size = 10303.2 
INFO  @ Wed, 14 Jul 2021 17:38:22: #1  total fragments in treatment: 25914096 
INFO  @ Wed, 14 Jul 2021 17:38:22: #1 user defined the maximum fragments... 
INFO  @ Wed, 14 Jul 2021 17:38:22: #1 filter out redundant fragments by allowing at most 1 identical fragment(s) 
INFO  @ Wed, 14 Jul 2021 17:39:00: #1  fragments after filtering in treatment: 25019384 
INFO  @ Wed, 14 Jul 2021 17:39:00: #1  Redundant rate of treatment: 0.03 
INFO  @ Wed, 14 Jul 2021 17:39:00: #1  total fragments in control: 22663234 
INFO  @ Wed, 14 Jul 2021 17:39:00: #1 user defined the maximum fragments... 
INFO  @ Wed, 14 Jul 2021 17:39:00: #1 filter out redundant fragments by allowing at most 1 identical fragment(s) 
INFO  @ Wed, 14 Jul 2021 17:39:34: #1  fragments after filtering in control: 22183414 
INFO  @ Wed, 14 Jul 2021 17:39:34: #1  Redundant rate of control: 0.02 
INFO  @ Wed, 14 Jul 2021 17:39:34: #1 finished! 
INFO  @ Wed, 14 Jul 2021 17:39:34: #2 Build Peak Model... 
INFO  @ Wed, 14 Jul 2021 17:39:34: #2 Skipped... 
INFO  @ Wed, 14 Jul 2021 17:39:34: #3 Call peaks... 
Traceback (most recent call last):
  File "/home/sylent/.conda/envs/conda-env/bin/macs3", line 727, in <module>
    main()
  File "/home/sylent/.conda/envs/conda-env/bin/macs3", line 48, in main
    run( args )
  File "/home/sylent/.conda/envs/conda-env/lib/python3.6/site-packages/MACS3/Commands/callpeak_cmd.py", line 249, in run
    peakdetect.call_peaks()
  File "MACS3/Signal/PeakDetect.pyx", line 112, in MACS3.Signal.PeakDetect.PeakDetect.call_peaks
  File "MACS3/Signal/PeakDetect.pyx", line 184, in MACS3.Signal.PeakDetect.PeakDetect.__call_peaks_w_control
AssertionError: 1000 can't be smaller than 10303.216796875!

**MACS2**
macs2 callpeak -f BAMPE -t bams/31Corr-Day2_H3K4me3_PF.maxL.bam -c bams/31Corr-Day1_IgG_PF.maxL.bam --outdir peaks -g hs -n 31Corr-Day2 -B -q 0.05

**ERROR:**
INFO  @ Wed, 14 Jul 2021 14:36:07: 22663234 fragments have been read. 
INFO  @ Wed, 14 Jul 2021 14:36:21: #1 mean fragment size is determined as 10303.2 bp from treatment 
INFO  @ Wed, 14 Jul 2021 14:36:21: #1 note: mean fragment size in control is 16011.8 bp -- value ignored 
INFO  @ Wed, 14 Jul 2021 14:36:21: #1 fragment size = 10303.2 
INFO  @ Wed, 14 Jul 2021 14:36:21: #1  total fragments in treatment: 25914096 
INFO  @ Wed, 14 Jul 2021 14:36:21: #1 user defined the maximum fragments... 
INFO  @ Wed, 14 Jul 2021 14:36:21: #1 filter out redundant fragments by allowing at most 1 identical fragment(s) 
INFO  @ Wed, 14 Jul 2021 14:37:03: #1  fragments after filtering in treatment: 25019384 
INFO  @ Wed, 14 Jul 2021 14:37:03: #1  Redundant rate of treatment: 0.03 
INFO  @ Wed, 14 Jul 2021 14:37:03: #1  total fragments in control: 22663234 
INFO  @ Wed, 14 Jul 2021 14:37:03: #1 user defined the maximum fragments... 
INFO  @ Wed, 14 Jul 2021 14:37:03: #1 filter out redundant fragments by allowing at most 1 identical fragment(s) 
INFO  @ Wed, 14 Jul 2021 14:37:40: #1  fragments after filtering in control: 22183414 
INFO  @ Wed, 14 Jul 2021 14:37:40: #1  Redundant rate of control: 0.02 
INFO  @ Wed, 14 Jul 2021 14:37:40: #1 finished! 
INFO  @ Wed, 14 Jul 2021 14:37:40: #2 Build Peak Model... 
INFO  @ Wed, 14 Jul 2021 14:37:40: #2 Skipped... 
INFO  @ Wed, 14 Jul 2021 14:37:40: #3 Call peaks... 
Traceback (most recent call last):
  File "/home/sylent/.conda/envs/conda-env/bin/macs2", line 653, in <module>
    main()
  File "/home/sylent/.conda/envs/conda-env/bin/macs2", line 51, in main
    run( args )
  File "/home/sylent/.conda/envs/conda-env/lib/python3.6/site-packages/MACS2/callpeak_cmd.py", line 256, in run
    peakdetect.call_peaks()
  File "MACS2/PeakDetect.pyx", line 107, in MACS2.PeakDetect.PeakDetect.call_peaks
  File "MACS2/PeakDetect.pyx", line 179, in MACS2.PeakDetect.PeakDetect.__call_peaks_w_control
AssertionError: 1000 can't be smaller than 10303.216796875!

I confirmed with predictd that fragment length was 170bp as expected from the library QC gels:
macs2 predictd -i bams/31Corr-Day2_H3K4me3_PF.maxL.bam -g hs
[SNIP]
INFO  @ Tue, 13 Jul 2021 18:17:14: 25914096 reads have been read. 
INFO  @ Tue, 13 Jul 2021 18:17:14: tag size is determined as 76 bps 
INFO  @ Tue, 13 Jul 2021 18:17:14: # tag size = 76 
INFO  @ Tue, 13 Jul 2021 18:17:14: # total tags in alignment file: 25914096 
INFO  @ Tue, 13 Jul 2021 18:17:14: # Build Peak Model... 
INFO  @ Tue, 13 Jul 2021 18:17:14: #2 looking for paired plus/minus strand peaks... 
INFO  @ Tue, 13 Jul 2021 18:17:18: #2 number of paired peaks: 49969 
INFO  @ Tue, 13 Jul 2021 18:17:18: start model_add_line... 
INFO  @ Tue, 13 Jul 2021 18:17:20: start X-correlation... 
INFO  @ Tue, 13 Jul 2021 18:17:20: end of X-cor 
INFO  @ Tue, 13 Jul 2021 18:17:20: # finished! 
INFO  @ Tue, 13 Jul 2021 18:17:20: # predicted fragment length is 170 bps 
INFO  @ Tue, 13 Jul 2021 18:17:20: # alternative fragment length(s) may be 170,349,535 bps 
INFO  @ Tue, 13 Jul 2021 18:17:20: # Generate R script for model : predictd 

I also used deeptools (see attached fragment size plot below) to assess fragment size.

Please let me know if this is a bug and/or how I can resolve this.
Thanks,
Piali

![fragmentSize](https://user-images.githubusercontent.com/7396915/125698550-32e720a1-2700-47b5-b1a4-45f081a8f902.png)

**Comment by taoliu** [comment]
It is really strange that MACS found the average insertion size over 10k from both treatment and control. Do you mind share with me part of the bam file so that I can reproduce the error? Thanks!

**Comment by KR-Chow** [comment]
> It is really strange that MACS found the average insertion size over 10k from both treatment and control. Do you mind share with me part of the bam file so that I can reproduce the error? Thanks!

I encounter the same error. The fragment size is ok too. That might be a bug?

**Comment by AZREALH** [comment]
I also encounter the error. How I can resolve it?
