### ISSUE TITLE
paired-end MeRIP-seq

### ISSUE THREAD

**Issue by BioEpi** [macs3-project/MACS#496]
Hello,
I have paired-end MeRIP-seq and input RNA-seq. the input files are bam files generated by Hisat2. When I ran MACS3 with -f BAM, it works. However, when setting -f to BAMPE, I got the following errors:
INFO @ Wed, 05 Jan 2022 08:14:44: #3 Call peaks...
Traceback (most recent call last):
File "/macs3", line 727, in
main()
File "/macs3", line 48, in main
run( args )
File "/MACS3/Commands/callpeak_cmd.py", line 249, in
run
peakdetect.call_peaks()
File "MACS3/Signal/PeakDetect.pyx", line 112, in MACS3.Signal.PeakDetect.PeakDetect.call_peaks
File "MACS3/Signal/PeakDetect.pyx", line 184, in MACS3.Signal.PeakDetect.PeakDetect.__call_peaks_w_control
AssertionError: 1000 can't be smaller than 2024.6768798828125!

Does it mean that MACS3 analyzes paired-end MeRIP-seq using -f BAM?
Best

**Additional context**
Add any other context or screenshots about your use case here.

**Comment by taoliu** [comment]
The error is caused by the fact that the average fragment length in the sample is 2024bps, and the default setting for estimating background noise with 'small local' (--slocal) of 1000bps is less than 2024.  As for MeRIP-seq (or RNA data), I don't feel the estimation of the local noise is necessary, therefore, you can disable it with `--nolambda`. Hopefully, you won't see such error.

**Comment by AZREALH** [comment]
> The error is caused by the fact that the average fragment length in the sample is 2024bps, and the default setting for estimating background noise with 'small local' (--slocal) of 1000bps is less than 2024. As for MeRIP-seq (or RNA data), I don't feel the estimation of the local noise is necessary, therefore, you can disable it with `--nolambda`. Hopefully, you won't see such error.

I encounter the same error, and `--nolambda` can't resolve it. How I can do?

**Comment by hlldhy** [comment]
> > The error is caused by the fact that the average fragment length in the sample is 2024bps, and the default setting for estimating background noise with 'small local' (--slocal) of 1000bps is less than 2024. As for MeRIP-seq (or RNA data), I don't feel the estimation of the local noise is necessary, therefore, you can disable it with `--nolambda`. Hopefully, you won't see such error.
> 
> I encounter the same error, and `--nolambda` can't resolve it. How can I do?

I encounter the same error, and --nolambda can't resolve it. How can I do?

**Comment by q1134269149** [comment]
I also encounter the same error. How can I do?
