### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by lionaid** [macs3-project/MACS#531]
**Describe the bug**
hmmratac crashes with ZeroDivisionError: float division

Execution of only one of my sample-sets (control condition aka static in this case) leads to a crash of MACS3. All other samples run fine.

Command 

The exact command for execution is:
`MACS3 hmmratac -b ./input/static/mpimg_L26666-1_LR2223-ATAC-LR2223-S15_S29_R1_001.trim.srt.nodup.no_chrM_MT.bam ./input/static/mpimg_L26666-1_LR2223-ATAC-LR2223-S39_S30_R1_001.trim.srt.nodup.no_chrM_MT.bam ./input/static/mpimg_L
26666-1_LR2223-ATAC-LR2223-S86_S31_R1_001.trim.srt.nodup.no_chrM_MT.bam --outdir static.pooled --save-digested --save-states`

**To Reproduce**
Steps to reproduce the behavior. If possible, could you share the data with us?

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Linux, Mac OSX]
 - Python version [e.g. 3.7.1]
 - Numpy version [e.g. 1.17.0]
 - MACS Version [e.g. 2.2.4]

**Additional context**

**Comment by zyaiqy** [comment]
I also encountered the same error message, is the problem solved?

**Comment by jeffhsu3** [comment]
Have a similar issue getting a zero division error, but not quite the same:
 ```INFO  @ Tue, 29 Nov 2022 11:03:12: 47534495 fragments have been read. 
INFO  @ Tue, 29 Nov 2022 11:03:33: #2 Use EM algorithm to estimate means and stddevs of fragment lengths 
INFO  @ Tue, 29 Nov 2022 11:03:33: #  for mono-, di-, and tri-nucleosomal signals... 
INFO  @ Tue, 29 Nov 2022 11:03:33: # A random seed 10151 has been used in the sampling function 
INFO  @ Tue, 29 Nov 2022 11:03:36: # Downsampled 0 fragments will be used for EM training... 
Traceback (most recent call last):
  File "/home/jeff/mambaforge/envs/align/bin/macs3", line 861, in <module>
    main()
  File "/home/jeff/mambaforge/envs/align/bin/macs3", line 101, in main
    run( args )
  File "/home/jeff/mambaforge/envs/align/lib/python3.10/site-packages/MACS3/Commands/hmmratac_cmd.py", line 119, in run
    em_trainer = HMMR_EM( petrack, options.em_means[1:4], options.em_stddevs[1:4], seed = options.hmm_randomSeed )
  File "MACS3/Signal/HMMR_EM.pyx", line 160, in MACS3.Signal.HMMR_EM.HMMR_EM.__init__
ZeroDivisionError: float division
```

- OS: Linux
- python 3.10.8
- numpy 1.23.5
- MACS 3.0.0b1

**Comment by philippadoherty** [comment]
Hi @lionaid, @zyaiqy, @jeffhsu3, thanks for raising this issue. This HMMRATAC command is still in beta testing. Can anyone please provide some testing data so we can reproduce the error on our end?

Thank you

**Comment by StevenKrzysztof** [comment]
Has this issue been solved? I've been using macs3 3.0.0b2 but still encounter that. I'm using this data from ENCODE: ENCFF346MIJ. You can get to the file by https://www.encodeproject.org/files/ENCFF346MIJ/   @philippadoherty 
Thank you!

**Comment by philippadoherty** [comment]
Hi @StevenKrzysztof, did you try using the `--cutoff-analysis-only` function that was added with the macs3 3.0.0b2 version? It can help to decide what `-l`, `-u`, and `-c` cutoffs to use. Also referenced here:  #559  

Thanks!

**Comment by StevenKrzysztof** [comment]
Hi @philippadoherty , I tried this command: macs3 hmmratac -b data/ATACseq.bam --cutoff-analysis-only
but still got zero division error

**Comment by philippadoherty** [comment]
Thanks @StevenKrzysztof, can you provide any additional info like your log/output for example?

**Comment by StevenKrzysztof** [comment]
Sure @philippadoherty . Here's the log file when I run 
[macs3_ATAC.log](https://github.com/macs3-project/MACS/files/12187746/macs3_ATAC.log)
Thanks

**Comment by taoliu** [comment]
@StevenKrzysztof It seems that there is an abnormally large 'fragment length' in the data can't be assigned to either short fragment, mono-nucleosome, di-nucleosome, or tri-nucleosome. I think the best way is to exclude such large fragments from the following steps in HMMRATAC.  Let me fix this before I release the next version. Thanks for the information!

**Comment by StevenKrzysztof** [comment]
@taoliu Thanks so much for your reply!

**Comment by macros29** [comment]
Actually, I made the mistake of using the GEX bam, which is single-read, instead of the ATAC bam. It works now once I swapped to the correct bam file. So the error was definitely due to the bam file not being PE.
