### ISSUE TITLE
Q: Error running macs3 callpeak

### ISSUE THREAD

**Issue by bodhi84** [macs3-project/MACS#554]
I have installed macs3 using pip. It is installed in a virtual environment. I tried to run this cmd:

macs3 callpeak -f BAMPE -t h2ak119ub_10A_R1.bam -g hs --broad

But I received the following error:

Traceback (most recent call last):
  File "/slipstream/home/bbanerje/MyPythonEnv/bin/macs3", line 861, in <module>
    main()
  File "/slipstream/home/bbanerje/MyPythonEnv/bin/macs3", line 48, in main
    from MACS3.Commands.callpeak_cmd import run
  File "/slipstream/home/bbanerje/MyPythonEnv/lib/python3.8/site-packages/MACS3/Commands/callpeak_cmd.py", line 24, in <module>
    from MACS3.Utilities.OptValidator import opt_validate_callpeak
  File "/slipstream/home/bbanerje/MyPythonEnv/lib/python3.8/site-packages/MACS3/Utilities/OptValidator.py", line 24, in <module>
    from MACS3.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "MACS3/IO/Parser.pyx", line 32, in init MACS3.IO.Parser
  File "MACS3/Signal/FixWidthTrack.pyx", line 28, in init MACS3.Signal.FixWidthTrack
  File "MACS3/Signal/Pileup.pyx", line 22, in init MACS3.Signal.Pileup
  File "MACS3/Signal/PairedEndTrack.pyx", line 27, in init MACS3.Signal.PairedEndTrack
  File "MACS3/Signal/BedGraph.pyx", line 23, in init MACS3.Signal.BedGraph
ImportError: /slipstream/home/bbanerje/MyPythonEnv/lib/python3.8/site-packages/MACS3/Signal/ScoreTrack.cpython-38-x86_64-linux-gnu.so: undefined symbol: __log_finite

Could you please help me out with a solution for this?

**Comment by My-laniaKeA** [comment]
I ran into exactly the same issue with numpy=1.24, python=3.9, Cython=0.29.36, hmmlearn=0.3.
`ImportError: /home/venv/lib/python3.9/site-packages/MACS3/Signal/ScoreTrack.cpython-39-x86_64-linux-gnu.so: undefined symbol: __log_finite`
