### ISSUE TITLE
Bug: can't install macs3 in a virtual environment via pip

### ISSUE THREAD

**Issue by yjhuh514** [macs3-project/MACS#558]
**Describe the bug**

Hello, I am having trouble with downloading MACS3 via pip.
I met all of the requirements in the "Install" documents.
Also, I made a virtual environment in python and tried to install MACS3 via `pip install MACS3` and there was an error as below.
Also, I downloaded the whole files in github and performed `$ python setup.py install` but it also failed.

**To Reproduce**
Steps to reproduce the behavior. If possible, could you share the data with us?

> error code as below.
-------------------
(myenv) D:\Dev\macs>pip install MACS3
Collecting MACS3
  Using cached MACS3-3.0.0b1.tar.gz (634 kB)
      Traceback (most recent call last):
        File "D:\Dev\macs\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Dev\macs\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Dev\macs\myenv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\yunju\AppData\Local\Temp\pip-build-env-v0i9wtin\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\yunju\AppData\Local\Temp\pip-build-env-v0i9wtin\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\yunju\AppData\Local\Temp\pip-build-env-v0i9wtin\overlay\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup            self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\yunju\AppData\Local\Temp\pip-build-env-v0i9wtin\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup  
          exec(code, locals())        File "<string>", line 155, in <module>
        File "<string>", line 91, in main
      KeyError: 'CC'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
-------------------
**Expected behavior**
-> to install MACS3

**Screenshots**
![image](https://user-images.githubusercontent.com/121819865/231142934-afbc9800-e65b-479d-a388-7db4e1552857.png)
![image](https://user-images.githubusercontent.com/121819865/231143058-a4b1bdc6-4e6b-48bd-be09-b9e60ed64923.png)

**System (please complete the following information):**
 - OS: Windows 11 (64bit)
 - Python version 3.11.2
 - Numpy version 1.24.2
 - MACS Version 3.0.0b1

**Additional context**

**Comment by philippadoherty** [comment]
Hi @yjhuh514 MACS is recommended to be used with either LinuxOS or MacOS, as Windows OS is not supported.
Similar issues: #444 and #540 - in #540 this was resolved by running Ubuntu in a virtual shell

Thanks
