### ISSUE TITLE
Bug: Getting requirements to build wheel ... error

### ISSUE THREAD

**Issue by bsunbo** [macs3-project/MACS#583]
Hi All, I am having issue with installing MACS3.  Really appreciated to have your help. Thanks!

-> pip list
Package    Version
---------- -------
Cython     0.29.24
pip        23.2.1
setuptools 65.5.0
-> pip install macs3
Collecting macs3
  Using cached MACS3-3.0.0b3.tar.gz (648 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\bosun\my_envMACS3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\bosun\my_envMACS3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bosun\my_envMACS3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bosun\AppData\Local\Temp\pip-build-env-vs508use\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bosun\AppData\Local\Temp\pip-build-env-vs508use\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\bosun\AppData\Local\Temp\pip-build-env-vs508use\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bosun\AppData\Local\Temp\pip-build-env-vs508use\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 156, in <module>
        File "<string>", line 72, in main
        File "C:\Users\bosun\AppData\Local\anaconda3\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bosun\AppData\Local\anaconda3\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bosun\AppData\Local\anaconda3\Lib\subprocess.py", line 1024, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\bosun\AppData\Local\anaconda3\Lib\subprocess.py", line 1509, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Additional context**

**Comment by philippadoherty** [comment]
Hi @bsunbo, can you please provide the following?
- OS: [e.g. Linux, Mac OSX]
- Python version [e.g. 3.7.1]
- Numpy version [e.g. 1.17.0]
Thanks

**Comment by bsunbo** [comment]
OS: 64-bit operating system, x64-based processor (Windows 11)
Python version: 3.11.3
Numpy version: 1.25.2

"Package       Version
------------- -------
cykhash       2.0.1
Cython        0.29.24
hmmlearn      0.3.0
joblib        1.3.1
numpy         1.25.2
pip           23.2.1
scikit-learn  1.3.0
scipy         1.11.1
setuptools    65.5.0
threadpoolctl 3.2.0"

Thank you.

**Comment by philippadoherty** [comment]
@bsunbo unfortunately Windows OS is not supported, MACS is recommended to be used with either LinuxOS or MacOS.
Another user was able to run Ubuntu in a virtual shell, seen in #540 and install that way.

Thanks.

**Comment by bsunbo** [comment]
I see. Thank you so much!!
