### ISSUE TITLE
Import Error when running Callpeaks update!

### ISSUE THREAD

**Issue by kshi219** [macs3-project/MACS#59]
I am running macs2 on a unix server... i tried both setup.py and setup_w_cython.py for installation, 
No apparent error were thrown during the installation

but when I use callpeaks 

kshi219@bugaboo:~/preprocess> macs2 callpeak -t wgEncodeSydhHistoneMcf7H3k09me3UcdAlnRep1.bam.gz.unique.tagAlign.gz -c wgEncodeSydhHistoneMcf7InputUcdAlnRep2.bam.gz.unique.tagAlign.gz -f BAM -n out -g hs -p 1e-2 --nomodel --extsize 73 -B --SPMR
Traceback (most recent call last):
  File "/home/kshi219/MACS/bin/macs2", line 615, in <module>
    main()
  File "/home/kshi219/MACS/bin/macs2", line 55, in main
    from MACS2.callpeak import run
  File "/home/kshi219/MACS/lib/python2.7/site-packages/MACS2/callpeak.py", line 30, in <module>
    from MACS2.OptValidator import opt_validate
  File "/home/kshi219/MACS/lib/python2.7/site-packages/MACS2/OptValidator.py", line 27, in <module>
    from MACS2.IO.cParser import BEDParser, ELANDResultParser, ELANDMultiParser, \
ImportError: /home/kshi219/MACS/lib/python2.7/site-packages/MACS2/IO/cParser.so: undefined symbol: __intel_sse2_strlen

sorry i was in the process of typing this out

**Comment by DrPraRam** [comment]
Hi there,

I am new to ATAC-seq data analysis. I have installed MACS2 using pip. I just ran callpeak function using treated and control bam files. I used the following command:
macs2 callpeak -t K-P-1.mapQabove10.RG.marked.sorted.bam -c K-P-9.mapQabove10.RG.marked.sorted.bam -f BAM -g hs -n K-P-1 -B -q 0.01

I am getting the following message and error:

Traceback (most recent call last):
File "/mnt/DATAPART3/local/bin/macs2", line 4, in
import('pkg_resources').run_script('MACS2==2.1.1.20160309', 'macs2')
File "/mnt/DATAPART3/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/init.py", line 744, in run_script
File "/mnt/DATAPART3/local/share/bcbio/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/init.py", line 1506, in run_script
File "/home/wenbin/.local/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 617, in

File "/home/wenbin/.local/lib/python2.7/site-packages/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg/EGG-INFO/scripts/macs2", line 56, in main

File "build/bdist.linux-x86_64/egg/MACS2/callpeak_cmd.py", line 31, in
File "build/bdist.linux-x86_64/egg/MACS2/OptValidator.py", line 27, in
File "build/bdist.linux-x86_64/egg/MACS2/IO/Parser.py", line 7, in
File "build/bdist.linux-x86_64/egg/MACS2/IO/Parser.py", line 6, in bootstrap
ImportError: /home/wenbin/.cache/Python-Eggs/MACS2-2.1.1.20160309-py2.7-linux-x86_64.egg-tmp/MACS2/IO/Parser.so: undefined symbol: PyFPE_jbuf

Please advice me on this. Thank you.

BR,
P

**Comment by mpallocc** [comment]
Hello, I am wondering whether the 

undefined symbol: __intel_sse2_strlen

on callpeak function has been tracked down for good.  

It is giving us nightmare on our computing cluster, and from the user's comments recompiling the source from scratch does not solve the issue. (also, that now does not contain C code, so it's  cython->gcc process)

thank you so much
