### ISSUE TITLE
Q: question about the libmvec.so.1 error.

### ISSUE THREAD

**Issue by Simple53** [macs3-project/MACS#604]
Hi, 
The Macs3 callpeak reported the error below:
```Traceback (most recent call last):
  File "/share/home/zhou3lab/zhangxinpei/bioapp/miniconda3/envs/macs3/bin/macs3", line 727, in <module>
    main()
  File "/share/home/zhou3lab/zhangxinpei/bioapp/miniconda3/envs/macs3/bin/macs3", line 47, in main
    from MACS3.Commands.callpeak_cmd import run
  File "/share/home/zhou3lab/zhangxinpei/bioapp/miniconda3/envs/macs3/lib/python3.8/site-packages/MACS3/Commands
    from MACS3.Utilities.OptValidator import opt_validate_callpeak
  File "/share/home/zhou3lab/zhangxinpei/bioapp/miniconda3/envs/macs3/lib/python3.8/site-packages/MACS3/Utilitie
    from MACS3.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "MACS3/IO/Parser.pyx", line 30, in init MACS3.IO.Parser
  File "MACS3/Signal/FixWidthTrack.pyx", line 28, in init MACS3.Signal.FixWidthTrack
  File "MACS3/Signal/Pileup.pyx", line 23, in init MACS3.Signal.Pileup
  File "MACS3/Signal/BedGraph.pyx", line 23, in init MACS3.Signal.BedGraph
  File "MACS3/Signal/ScoreTrack.pyx", line 23, in init MACS3.Signal.ScoreTrack
ImportError: libmvec.so.1: cannot open shared object file: No such file or directory
```

**Comment by taoliu** [comment]
@Simple53 Could you use the following template for 'bug report' to provide more detail on this issue? Thank you!

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior. If possible, could you share the data with us?

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. Linux, Mac OSX] [note: Windows NOT supported]
 - Python version [e.g. 3.7.1]
 - Numpy version [e.g. 1.17.0]
 - MACS Version [e.g. 2.2.4]

**Additional context**
Add any other context about the problem here.

**Comment by yikiii** [comment]
> @Simple53 Could you use the following template for 'bug report' to provide more detail on this issue? Thank you!
> 
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior. If possible, could you share the data with us?
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **System (please complete the following information):**
> 
> * OS: [e.g. Linux, Mac OSX] [note: Windows NOT supported]
> * Python version [e.g. 3.7.1]
> * Numpy version [e.g. 1.17.0]
> * MACS Version [e.g. 2.2.4]
> 
> **Additional context** Add any other context about the problem here.

**same problem, installed with conda**


```
         source /nfs3/public2/User/user/miniconda3/bin/activate macs3 && \
         macs3 callpeak -t /nfs6/public2/User/user/project//03.bam/bam/sh_IP.bam -c /nfs6/public2/User/user/project/03.bam/bam/sh_input1.bam -f BAMPE -g mm --outdir /nfs6/public2/User/user/test/peak2/ -q 0.05 -n S -B 2> /nfs6/public2/User/user/test/peak2/sh_macs3.log
```


```
Traceback (most recent call last):
  File "/nfs3/public2/User/user/miniconda3/envs/macs3/bin/macs3", line 727, in <module>
    main()
  File "/nfs3/public2/User/user/miniconda3/envs/macs3/bin/macs3", line 47, in main
    from MACS3.Commands.callpeak_cmd import run
  File "/nfs3/public2/User/user/miniconda3/envs/macs3/lib/python3.8/site-packages/MACS3/Commands/callpeak_cmd.py", line 24, in <module>
    from MACS3.Utilities.OptValidator import opt_validate_callpeak
  File "/nfs3/public2/User/user/miniconda3/envs/macs3/lib/python3.8/site-packages/MACS3/Utilities/OptValidator.py", line 24, in <module>
    from MACS3.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "MACS3/IO/Parser.pyx", line 30, in init MACS3.IO.Parser
  File "MACS3/Signal/FixWidthTrack.pyx", line 28, in init MACS3.Signal.FixWidthTrack
  File "MACS3/Signal/Pileup.pyx", line 23, in init MACS3.Signal.Pileup
  File "MACS3/Signal/BedGraph.pyx", line 23, in init MACS3.Signal.BedGraph
  File "MACS3/Signal/ScoreTrack.pyx", line 23, in init MACS3.Signal.ScoreTrack
ImportError: libmvec.so.1: cannot open shared object file: No such file or directory

```

**Comment by matteozoia4** [comment]
Got the same issue using Macs3.

Linux
Conda=4.14.0
Python=3.8.18
Macs3=3.0.0a6

**Comment by slives-lab** [comment]
Is there a fix for this issue? I have encountered the error using macs3.

###
ImportError: libmvec.so.1: cannot open shared object file: No such file or directory
###
macs3 3.0.0a6
Python 3.8.20
centOS
conda 22.9.0
###

Traceback (most recent call last):
  File "/bin/macs3", line 727, in <module>
    main()
  File "/bin/macs3", line 55, in main
    from MACS3.Commands.bdgpeakcall_cmd import run
  File "/lib/python3.8/site-packages/MACS3/Commands/bdgpeakcall_cmd.py", line 17, in <module>
    from MACS3.IO import BedGraphIO
  File "MACS3/IO/BedGraphIO.pyx", line 17, in init MACS3.IO.BedGraphIO
  File "MACS3/Signal/BedGraph.pyx", line 23, in init MACS3.Signal.BedGraph
  File "MACS3/Signal/ScoreTrack.pyx", line 23, in init MACS3.Signal.ScoreTrack
ImportError: libmvec.so.1: cannot open shared object file: No such file or directory

**Comment by philippadoherty** [comment]
Hello, `libmvec.so.1` is part of the GNU C Library (`glibc`). You may need to:

1.  check that glibc is installed, 
2. or check that your conda environment is correctly configured to find it if it already exists, 
3. or it may need to be updated to ensure that `glibc` contains `libmvec.so.1`.

Please let me know if that resolves the issue. 

Thank you
