### ISSUE TITLE
 macs2 callpeak AttributeError: 'Namespace'

### ISSUE THREAD

**Issue by y-mone** [macs3-project/MACS#61]
When I run macs2 to call peak with this command

GEN_SIZE=0.4379e9
PVALUE=1e-5
macs2 callpeak -t "FAI/FAI-FM1.bam" -c "FAI/FAI-IM.bam" -n "FAI/FAI-IM-FM1_macs_p05" -f BAM -g "$GEN_SIZE" -p "$PVALUE" 2> FAI-IM-FM1_macs_p05.log

 I get this error message:

Traceback (most recent call last):
  File "/local/peakseq/MACS-2/bin/macs2", line 337, in <module>
    main()
  File "/local/peakseq/MACS-2/bin/macs2", line 54, in main
    run( args )
  File "/local/python/2.7-bis/lib/python2.7/site-packages/MACS2/callpeak.py", line 55, in run
    options = opt_validate( args )
  File "/local/python/2.7-bis/lib/python2.7/site-packages/MACS2/OptValidator.py", line 132, in opt_validate
    options.peakxls = os.path.join( options.outdir, options.name+"_peaks.xls" )
AttributeError: 'Namespace' object has no attribute 'outdir'

Is there something wrong with my input? Could you explain to me, please.

**Comment by ignaciot** [comment]
I'm also experiencing this error using:

`$ macs2 callpeak --nomodel --format SAM -t /path/to/somefile.sam --shift -100 --extsize 200 -B --broad --outdir /the/output/dir/`

I do have permissions the source file and output directory. Is this a bug or is there something wrong in the arguments? (build 2.1.1.20160309)

**Comment by taoliu** [comment]
@ignaciot It may be a different thing. Could you post your error message?

**Comment by jshireman5** [comment]
Traceback (most recent call last):
  File "/usr/bin/macs2", line 614, in <module>
    main()
  File "/usr/bin/macs2", line 56, in main
    run( args )
  File "/usr/local/lib/python2.7/dist-packages/MACS2/callpeak_cmd.py", line 68, in run
    tempfile.tempdir = options.tempdir
AttributeError: 'Namespace' object has no attribute 'tempdir'


This is the error i get i seem to be having the same problem
