### ISSUE TITLE
Bug: OverflowError when running hmmratac

### ISSUE THREAD

**Issue by atj31** [macs3-project/MACS#649]
I'm trying to run hmmratac to call peaks from my bampe files the code I used is 
hmmratac -i Alignments/file.bam -f BAMPE --outdir Peaks/ -n name

It runs for a long time but I get an 'OverflowError: signed integer is greater than maximum' error

I tried to troubleshoot but unsure how to proceed - I can run the callpeak on the same bampe file without any issues. 

Thank you in advance!

The whole running code pasted below:
[...]
INFO  @ 19 Jun 2024 15:58:13: [428 MB]  37000000 fragments parsed
INFO  @ 19 Jun 2024 15:58:16: [434 MB]  38000000 fragments parsed
INFO  @ 19 Jun 2024 15:58:19: [441 MB] 38850552 fragments have been read.
INFO  @ 19 Jun 2024 15:58:50: [441 MB] #2 Use EM algorithm to estimate means and stddevs of fragment lengths
INFO  @ 19 Jun 2024 15:58:50: [441 MB] #  for mono-, di-, and tri-nucleosomal signals...
INFO  @ 19 Jun 2024 15:58:50: [441 MB] # A random seed 10151 has been used in the sampling function
INFO  @ 19 Jun 2024 15:58:54: [491 MB] # Downsampled 1336693 fragments will be used for EM training...
INFO  @ 19 Jun 2024 16:02:48: [491 MB] # Reached convergence after 11 iterations
INFO  @ 19 Jun 2024 16:02:48: [491 MB] #  The means and stddevs after EM:
INFO  @ 19 Jun 2024 16:02:48: [491 MB] #                         short       mono         di        tri
INFO  @ 19 Jun 2024 16:02:48: [491 MB] #             means:         50      173.9      381.2        600
INFO  @ 19 Jun 2024 16:02:48: [491 MB] #           stddevs:         20       53.6       51.4         20
INFO  @ 19 Jun 2024 16:02:48: [491 MB] #  Compute the weights for each fragment length for each of the four signal types
INFO  @ 19 Jun 2024 16:02:55: [491 MB] #  Generate short, mono-, di-, and tri-nucleosomal signals
Traceback (most recent call last):
  File "/mnt/data/Utils/python_environ/macs3/bin/macs3", line 1028, in <module>
    main()
  File "/mnt/data/Utils/python_environ/macs3/bin/macs3", line 101, in main
    run( args )
  File "/mnt/data/Utils/python_environ/macs3/lib/python3.9/site-packages/MACS3/Commands/hmmratac_cmd.py", line 155, in run
    digested_atac_signals = generate_digested_signals( petrack, weight_mapping )
  File "MACS3/Signal/HMMR_Signal_Processing.pyx", line 106, in MACS3.Signal.HMMR_Signal_Processing.generate_digested_signals
  File "MACS3/Signal/HMMR_Signal_Processing.pyx", line 129, in MACS3.Signal.HMMR_Signal_Processing.generate_digested_signals
  File "MACS3/Signal/BedGraph.pyx", line 219, in MACS3.Signal.BedGraph.bedGraphTrackI.add_chrom_data_hmmr_PV
  File "MACS3/Signal/BedGraph.pyx", line 232, in MACS3.Signal.BedGraph.bedGraphTrackI.add_chrom_data_hmmr_PV
OverflowError: signed integer is greater than maximum

**Comment by callum-b** [comment]
I am getting the same bug for one of my replicates of ATACseq. Similarly, it is reading all 34 169 734 fragments, and when it moves on to generate the different signals it crashes with the same error message and stack.
My other two replicates for this assay are processed fine (and have a similar number of reads, if not more), and the BAMPE file used for this replicate can be processed by filterdup without issue, so I do not know where this is coming from.

**Comment by vanottee** [comment]
Same error for me:

----
code:

conda activate MACS3

macs3 hmmratac -i ~/ABW1filteredd.bam ~/ABW2filteredd.bam -e ~/genomes/blacklist/mm10-blacklist.v2.bed -u 40 -l 10 -c 5 -n ABW_all_filtered

----
End of job error:

INFO  @ 30 May 2025 12:49:15: [1083 MB] 59923182 fragments have been read. 
INFO  @ 30 May 2025 12:51:10: [1083 MB] #  Read 117529790 fragments. 
INFO  @ 30 May 2025 12:51:10: [1083 MB] #  Read blacklist file... 
Traceback (most recent call last):
  File "/miniconda3/envs/MACS3/bin/macs3", line 1017, in <module>
    main()
  File "/miniconda3/envs/MACS3/bin/macs3", line 103, in main
    run(args)
  File "/miniconda3/envs/MACS3/lib/python3.10/site-packages/MACS3/Commands/hmmratac_cmd.py", line 153, in run
    petrack.exclude(blacklist_regions)
  File "MACS3/Signal/PairedEndTrack.py", line 271, in MACS3.Signal.PairedEndTrack.PETrackI.exclude
  File "MACS3/Signal/PairedEndTrack.py", line 331, in MACS3.Signal.PairedEndTrack.PETrackI.exclude
OverflowError: Python integer 17538701711 out of bounds for int32
