### ISSUE TITLE
Bug: Overflow error when using Poisson law for bdgcmp

### ISSUE THREAD

**Issue by callum-b** [macs3-project/MACS#667]
I'm trying to run bdgcmp on some spike-in normalised bedGraphs I've generated used MACS3 tools. Here is the command line I'm running:
`macs3 bdgcmp -m qpois -t DATA/BED/TEAD1/TEAD1_T1_pos_1_pileup_GRCh38_sort_spikeBDGP6.32_pe.bedGraph -c DATA/BED/TEAD1/Input_T1_pos_pe_pileup_sort_norm10M_nozero.bedGraph -o DATA/BED/TEAD1/TEAD1_T1_pos_1_pileup_GRCh38_sort_spikeBDGP6.32_pe_qval.bedGraph`

Here's the output from MACS3:

```
INFO
@ 21 Oct 2024 17:49:30: [38 MB] Read and build treatment bedGraph...
INFO
@ 21 Oct 2024 17:49:32: [65 MB] Read and build control bedGraph...
INFO
@ 21 Oct 2024 17:49:35: [96 MB] Build ScoreTrackII...
INFO
@ 21 Oct 2024 17:49:38: [154 MB] Calculate scores comparing treatment and control by 'qpois'...
Traceback (most recent call last):
File "MACS3/Signal/ScoreTrack.pyx", line 67, in MACS3.Signal.ScoreTrack.get_pscore
File "src/cykhash/maps/map_impl.pxi", line 2448, in cykhash.khashmaps.PyObjectMap.__getitem__
File "src/cykhash/maps/map_impl.pxi", line 2445, in cykhash.khashmaps.PyObjectMap.cget
KeyError: (-2147483648, 0.009999999776482582)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/bioinfo/src/MACS/MACS-v3.0.0/MACS-v3.0.0_venv/bin/macs3", line 1028, in <module>
main()
File "/usr/local/bioinfo/src/MACS/MACS-v3.0.0/MACS-v3.0.0_venv/bin/macs3", line 65, in main
run( args )
File "/usr/local/bioinfo/src/MACS/MACS-v3.0.0/MACS-v3.0.0_venv/lib/python3.11/site-packages/MACS3/Commands/bdgcmp_cmd.py", line 72, in run
sbtrack.change_score_method( ord('q') )
File "MACS3/Signal/ScoreTrack.pyx", line 354, in MACS3.Signal.ScoreTrack.ScoreTrackII.change_score_method
File "MACS3/Signal/ScoreTrack.pyx", line 371, in MACS3.Signal.ScoreTrack.ScoreTrackII.change_score_method
File "MACS3/Signal/ScoreTrack.pyx", line 407, in MACS3.Signal.ScoreTrack.ScoreTrackII.compute_pvalue
File "MACS3/Signal/ScoreTrack.pyx", line 69, in MACS3.Signal.ScoreTrack.get_pscore
File "MACS3/Signal/Prob.pyx", line 209, in MACS3.Signal.Prob.poisson_cdf
OverflowError: can't convert negative value to npy_uint32
```
I tried running the same command on a subset of the bedGraphs (chr15) and got the same behaviour, so I don't think it's tied to the size of the file/number of reads, which was my first thought given the Overflow error. These files can be downloaded [here](https://drive.google.com/file/d/1HRv7BjGYiXTFfosZ1ACZ62oI3U4gOk9k/view?usp=sharing) and [here](https://drive.google.com/file/d/1VAxM-vkkhRGqVGk_AARAg-0HpI4JSfwq/view?usp=sharing) in gzipped format.

bdgcmp does however work when using `-m subtract`, so it probably isn't coming from the data files I'm processing.

What's happening with the Poisson law in bdgcmp? Why is it failing?

**System**
 - OS: Ubuntu 20.04.6 LTS
 - Python version: 3.10.14
 - Numpy version: 1.23.5
 - MACS Version: 3.0.1

**Comment by taoliu** [comment]
@callum-b May I ask why the values in the treatment file 'TEAD1_T1_pos_1_pileup_GRCh38_sort_spikeBDGP6.32_pe.bedGraph' is extremely high? The value is either 0 or larger than 1e+7. 
```
$ cut -f 4 -d" " TEAD1_T1_pos_1_pileup_GRCh38_sort_spikeBDGP6.32_pe_chr15.bedGraph | sort -u -g | head -10
0
1.21207e+07
2.42414e+07
3.63621e+07
4.84827e+07
6.06034e+07
7.27241e+07
8.48448e+07
9.69655e+07
1.09086e+08
```

But the control file  'Input_T1_pos_pe_pileup_sort_norm10M_nozero.bedGraph' contains value ranging from 0.01 to 8.5. Before `bdgcmp`, the two pileup files need to be [normalized](https://macs3-project.github.io/MACS/docs/Advanced_Step-by-step_Peak_Calling.html#step-5-scale-the-chip-and-control-to-the-same-sequencing-depth).

**Comment by taoliu** [comment]
@callum-b The overflow error may be due to the big difference between treatment and control pileup.

**Comment by AndHerr** [comment]
Hello, and thank you very much for MACS — it’s fantastic! I’ve been using MACS2 for a while, and it’s great work. I’m now jumping to MACS3. I’ve followed the tutorial steps, but I’ve encountered an issue while running:

macs3 bdgcmp -t treatment.bdg -c treament_control_local_lambda.bdg -m ppois -o out.bdg

treatment.bdg was generated with macs3 pileup
treament_control_local_lambda.bdg was generated as described in the tutorial.

INFO  @ 25 May 2026 12:18:01: [26 MB] Read and build treatment bedGraph... 
INFO  @ 25 May 2026 12:18:30: [309 MB] Read and build control bedGraph... 
INFO  @ 25 May 2026 12:18:51: [507 MB] Build ScoreTrackII... 
INFO  @ 25 May 2026 12:19:27: [1228 MB] Calculate scores comparing treatment and control by 'ppois'... 
Traceback (most recent call last):
  File "MACS3/Signal/ScoreTrack.py", line 74, in MACS3.Signal.ScoreTrack.get_pscore
    return pscore_dict[(observed, expectation)]
  File "src/cykhash/maps/map_impl.pxi", line 2448, in cykhash.khashmaps.PyObjectMap.__getitem__
  File "src/cykhash/maps/map_impl.pxi", line 2445, in cykhash.khashmaps.PyObjectMap.cget
KeyError: (0, 0.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/X/snakemake/.snakemake/conda/858d90ef79e3ab007d93ea8265a2f1ed/bin/macs3", line 1026, in <module>
    main()
    ~~~~^^
  File "/X/snakemake/.snakemake/conda/858d90ef79e3ab007d93ea8265a2f1ed/bin/macs3", line 67, in main
    run(args)
    ~~~^^^^^^
  File "/X/snakemake/.snakemake/conda/858d90ef79e3ab007d93ea8265a2f1ed/lib/python3.13/site-packages/MACS3/Commands/bdgcmp_cmd.py", line 70, in run
    sbtrack.change_score_method(ord('p'))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "MACS3/Signal/ScoreTrack.py", line 369, in MACS3.Signal.ScoreTrack.ScoreTrackII.change_score_method
  File "MACS3/Signal/ScoreTrack.py", line 385, in MACS3.Signal.ScoreTrack.ScoreTrackII.change_score_method
    self.compute_pvalue()
  File "MACS3/Signal/ScoreTrack.py", line 430, in MACS3.Signal.ScoreTrack.ScoreTrackII.compute_pvalue
    v[i] = get_pscore(cython.cast(cython.int,
  File "MACS3/Signal/ScoreTrack.py", line 76, in MACS3.Signal.ScoreTrack.get_pscore
    score = -1 * poisson_cdf(observed,
  File "MACS3/Signal/Prob.py", line 252, in MACS3.Signal.Prob.poisson_cdf
  File "MACS3/Signal/Prob.py", line 269, in MACS3.Signal.Prob.poisson_cdf
    assert lam > 0.0, "Lambda must > 0, however we got %d" % lam
AssertionError: Lambda must > 0, however we got 0

Checking the files, they don’t appear to be substantially different (see below). However, I should note that I used the ratio of spike-in reads rather than actual host reads to generate the local_lambda file. This resulted in a noticeably higher number of reads in the control compared to the treatment. I'm unsure if that's causing the issue.

>cat treatment.bdp | head  -10
1	0	10088	0.00000
1	10088	10150	1.00000
1	10150	10187	2.00000
1	10187	10189	3.00000
1	10189	10199	4.00000
1	10199	10207	5.00000
1	10207	10247	4.00000
1	10247	10278	5.00000
1	10278	10295	6.00000
1	10295	10302	5.00000

>cat treament_control_local_lambda.bdg | head -10
track type=bedGraph name="MULTIPLY_modified_scores" description="Scores calculated by MULTIPLY" visibility=2 alwaysZero=on
1	0	10059	0.00000
1	10059	10064	0.57510
1	10064	10066	0.86265
1	10066	10067	1.43776
1	10067	10069	1.72531
1	10069	10070	2.01286
1	10070	10071	2.30041
1	10071	10073	2.58796
1	10073	10078	3.16306


Many thanks!!

**Comment by taoliu** [comment]
@AndHerr It seems that the lambda of poisson test is 0 for some regions, and that fact caused the assertion error. Normally, if the background noise track (control_lambda) was generated by MACS3, the minimal value of lambda should always be a positive number. Since you made your own control lambda file, you may try to set certain psuedocount through `-p` option to avoid this error. The pseudocount can be the genome-wide average signal such as total_reads*fragment_size/genome_size.
